import XCTest
@testable import RinaCore

/// Guards the `.rinalive` scripts that ship in the app bundle.
///
/// These are generated by `tools/convert_upstream_timelines.py` from
/// 738NGX/RinaChanBoard's keyframe timelines. A converter change, a parts
/// library change, or a hand edit that breaks one of them would otherwise only
/// surface as a runtime error on the 演出 tab, on a device, in front of a user.
final class BundledPerformanceTests: XCTestCase {
    private static var resourcesURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // BundledPerformanceTests.swift -> RinaCoreTests/
            .deletingLastPathComponent() // RinaCoreTests -> Tests/
            .deletingLastPathComponent() // Tests -> RinaCore/ (package root)
            .deletingLastPathComponent() // RinaCore -> Packages/
            .deletingLastPathComponent() // Packages -> ios/
            .appendingPathComponent("RinaBoard/Resources")
    }

    private func loadLibrary() throws -> PartsLibrary? {
        let url = Self.resourcesURL.appendingPathComponent("expression_parts.json")
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try PartsLibrary(jsonData: data)
    }

    private func scriptURLs() throws -> [URL] {
        let contents = try FileManager.default.contentsOfDirectory(at: Self.resourcesURL,
                                                                   includingPropertiesForKeys: nil)
        return contents.filter { $0.pathExtension == "rinalive" }.sorted { $0.path < $1.path }
    }

    func testEveryBundledScriptParses() throws {
        guard let library = try loadLibrary() else { throw XCTSkip("expression_parts.json not available") }
        let urls = try scriptURLs()
        XCTAssertFalse(urls.isEmpty, "no .rinalive scripts found in Resources")

        for url in urls {
            let text = try String(contentsOf: url, encoding: .utf8)
            let name = url.lastPathComponent
            do {
                let script = try LivePerformanceScriptParser.parse(text, library: library)
                XCTAssertFalse(script.keyframes.isEmpty, "\(name) has no keyframes")
                XCTAssertGreaterThan(script.durationMs, 0, "\(name) has zero duration")
                XCTAssertEqual(script.fps, 10, "\(name) is not at the upstream 10 fps")

                // Strictly increasing frames is the invariant `index(atMs:)`'s
                // binary search rests on; the converter collapses upstream's
                // duplicate frames, so a regression there would land here.
                let frames = script.keyframes.map(\.frame)
                XCTAssertEqual(frames, frames.sorted(), "\(name) keyframes are out of order")
                XCTAssertEqual(Set(frames).count, frames.count, "\(name) has duplicate frames")

                // A *fully* dark keyframe is legal — upstream uses the blank
                // part id `0` for blackout beats (`solo1` has two) — but a
                // script that composes nothing anywhere would mean the part
                // ids stopped resolving, which is the failure worth catching.
                let composed = script.composedFrames(using: library)
                XCTAssertEqual(composed.count, script.keyframes.count, "\(name) composed count mismatch")
                XCTAssertTrue(composed.contains { $0.litCount > 0 },
                              "\(name) composes no lit LEDs at all")
                let darkCount = composed.filter { $0.litCount == 0 }.count
                XCTAssertLessThan(darkCount, composed.count / 10,
                                  "\(name) is mostly dark (\(darkCount)/\(composed.count)) — ids likely stopped resolving")
            } catch {
                XCTFail("\(name) failed to parse: \(error)")
            }
        }
    }

    /// Cross-checks our lookup against upstream's own playback algorithm.
    ///
    /// 738NGX plays a timeline by polling the audio clock and doing an exact
    /// dictionary match (`MusicPage.cs:31` + `TimeLine.cs`):
    ///
    ///     int frame = Mathf.FloorToInt(musicSource.time * 10);
    ///     if (contentHash.TryGetValue(frame, out index)) { current = index; }
    ///     // otherwise the previous face is held
    ///
    /// We instead binary-search for the last keyframe at or before the current
    /// position. The two are equivalent — `f <= floor(ms/100)` and
    /// `f * 100 <= ms` say the same thing for integer `f` — but "should be
    /// equivalent" is exactly the kind of claim that rots, and a divergence
    /// would show up as the board drifting a beat off the music. So this
    /// replays upstream's algorithm over every bundled script, at 10 ms steps
    /// across the whole performance, and asserts the two never disagree.
    ///
    /// Our version is also strictly more robust: upstream *misses* a keyframe
    /// entirely if its `Update()` ever steps over that frame number, while a
    /// search for "the last one at or before now" cannot.
    func testLookupMatchesUpstreamExactFramePolling() throws {
        guard let library = try loadLibrary() else { throw XCTSkip("expression_parts.json not available") }

        for url in try scriptURLs() {
            let name = url.lastPathComponent
            let text = try String(contentsOf: url, encoding: .utf8)
            let script = try LivePerformanceScriptParser.parse(text, library: library)

            // Upstream's `contentHash`: frame number -> keyframe index.
            var byFrame: [Int: Int] = [:]
            for (index, keyframe) in script.keyframes.enumerated() {
                byFrame[keyframe.frame] = index
            }

            var upstreamCurrent: Int?
            var checked = 0
            for ms in stride(from: 0, through: script.durationMs + 500, by: 10) {
                // Upstream: floor(seconds * fps), exact match, else hold.
                let frame = ms * script.fps / 1000
                if let index = byFrame[frame] { upstreamCurrent = index }

                XCTAssertEqual(script.index(atMs: ms), upstreamCurrent,
                               "\(name) diverges from upstream polling at \(ms) ms")
                checked += 1
            }
            XCTAssertGreaterThan(checked, 100, "\(name) was barely sampled")
        }
    }

    func testCatalogMatchesTheScriptsOnDisk() throws {
        let catalogURL = Self.resourcesURL.appendingPathComponent("preset_live_catalog.json")
        guard let data = try? Data(contentsOf: catalogURL) else {
            throw XCTSkip("preset_live_catalog.json not available")
        }

        struct Entry: Decodable {
            let file: String
            let title: String
            let keyframes: Int
            let durationMs: Int
        }
        let catalog = try JSONDecoder().decode([Entry].self, from: data)
        XCTAssertFalse(catalog.isEmpty)

        guard let library = try loadLibrary() else { throw XCTSkip("expression_parts.json not available") }
        for entry in catalog {
            let url = Self.resourcesURL.appendingPathComponent("\(entry.file).rinalive")
            XCTAssertTrue(FileManager.default.fileExists(atPath: url.path),
                          "catalog lists \(entry.file) but the script is missing")
            guard let text = try? String(contentsOf: url, encoding: .utf8),
                  let script = try? LivePerformanceScriptParser.parse(text, library: library) else {
                XCTFail("\(entry.file) did not parse")
                continue
            }
            XCTAssertEqual(script.keyframes.count, entry.keyframes, "\(entry.file) keyframe count drifted")
            XCTAssertEqual(script.durationMs, entry.durationMs, "\(entry.file) duration drifted")
            XCTAssertEqual(script.title, entry.title, "\(entry.file) title drifted")
            XCTAssertFalse(entry.title.isEmpty)
        }
    }
}
