# ---------------------------------------------------------------------------
# config.py
#
# Central project constants.
# ---------------------------------------------------------------------------

import demo_faces

POLL_PERIOD_MS = 10
SETTINGS_FILE = "linaboard_settings.json"

DEFAULT_FACE = demo_faces.DEFAULT_FACE_INDEX
NUM_FACES = len(demo_faces.FRAMES)

DEFAULT_INTERVAL_S = 1.0
INTERVAL_STEP_S = 0.5
INTERVAL_MIN_S = 0.5
INTERVAL_MAX_S = 10.0

DEMO_DEFAULT_INTERVAL_S = 5.0
DEMO_DEFAULT_AUTO = True

DEFAULT_BRIGHTNESS = 50
BRIGHTNESS_STEP = 10
BRIGHTNESS_MIN = 10
BRIGHTNESS_MAX = 100

FLASH_HOLD_MS = 1000
B6_LONG_PRESS_MS = 700
SPECIAL_COMBO_LONG_PRESS_MS = 2000
BADAPPLE_COMBO_LONG_PRESS_MS = 2000

BATTERY_REFRESH_MS = 150
BATTERY_DISPLAY_MEAN_WINDOW_MS = 450
BATTERY_DISPLAY_MEAN_SAMPLE_DELAY_MS = 15
BATTERY_DISPLAY_CYCLE_MS = 2000
BATTERY_LOG_INTERVAL_MS = 30000
BATTERY_RELEARN_EVERY_MEASUREMENTS = 1000
BATTERY_RELEARN_MAX_STEP_V = 0.05
BATTERY_RELEARN_MIN_STEP_V = 0.05
BATTERY_RELEARN_HOLDOFF_MEASUREMENTS = 20
BATTERY_MIN_SPAN_V = 0.20

BATTERY_PERCENT_CURVE = (
    (0.00, 0.0),
    (0.08, 4.0),
    (0.18, 12.0),
    (0.30, 26.0),
    (0.45, 45.0),
    (0.60, 63.0),
    (0.74, 79.0),
    (0.86, 91.0),
    (0.94, 97.0),
    (1.00, 100.0),
)

BATTERY_HISTORY_MAX_SAMPLES = 96
BATTERY_HISTORY_MIN_RATE_PCT_PER_H = 0.25
BATTERY_HISTORY_SAME_MODE_WEIGHT = 2.5
BATTERY_HISTORY_BRIGHTNESS_WINDOW = 20
BATTERY_DEFAULT_USAGE_HOURS = 1.0
BATTERY_DEFAULT_CHARGE_HOURS = 0.5

BATTERY_ADC_GPIO = 26
BATTERY_ADC_REF_V = 3.3
BATTERY_SAMPLES = 16
BATTERY_DIVIDER_R1 = 100000
BATTERY_DIVIDER_R2 = 57000
BATTERY_DEFAULT_MIN_V = 6.6
BATTERY_DEFAULT_MAX_V = 8.0
BATTERY_DISPLAY_TOL_V = 0.12

CHARGE_DETECT_ADC_GPIO = 27
CHARGE_DETECT_ADC_REF_V = 3.3
CHARGE_DETECT_SAMPLES = 16
CHARGE_DETECT_DIVIDER_R1 = 270000
CHARGE_DETECT_DIVIDER_R2 = 47000
CHARGE_DETECT_NON_CHARGING_V = 3.0
CHARGE_DETECT_CHARGING_MIN_V = 4.5
CHARGE_DISPLAY_THRESHOLD_V = 4.5
CHARGE_DETECT_HYSTERESIS_LOW_V = 3.0


BATTERY_CHARGE_ANIM_INTERVAL_EMPTY_S = 0.2
BATTERY_CHARGE_ANIM_INTERVAL_NEAR_FULL_S = 0.2
BATTERY_CHARGE_ANIM_NEAR_FULL_PERCENT = 90
BATTERY_CHARGE_LAST_COLUMN_FLASH_MS = 300

EDGE_FLASH_ATTACK_MS = 45
EDGE_FLASH_DECAY_MS = 260
EDGE_FLASH_TOTAL_MS = EDGE_FLASH_ATTACK_MS + EDGE_FLASH_DECAY_MS
EDGE_FLASH_COLOR = (0, 120, 255)

BADAPPLE_PART_MODULES = (
    'badapple_part0', 'badapple_part1', 'badapple_part2', 'badapple_part3',
    'badapple_part4', 'badapple_part5', 'badapple_part6', 'badapple_part7',
    'badapple_part8', 'badapple_part9', 'badapple_part10', 'badapple_part11',
    'badapple_part12', 'badapple_part13', 'badapple_part14', 'badapple_part15',
    'badapple_part16',
)
BADAPPLE_ON_COLOR = (255, 255, 255)
BADAPPLE_OFF_COLOR = (0, 0, 0)
BADAPPLE_BRIGHTNESS_DIVISOR = 2
