[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_ldf_mode = chain+
lib_deps =
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    bblanchon/ArduinoJson
    makuna/NeoPixelBus

lib_ignore =
    WiFiManager
    ESP_WiFiManager
    WiFiManager_Generic
    AutoConnect
    IotWebConf

build_flags =
    -D RINACHAN_AP_ONLY=1
    -D WIFI_MANAGER_DISABLED=1
    -D CORE_DEBUG_LEVEL=3
