import Foundation

/// Source facts for the background star field on
/// https://lovelive-as.bushimo.jp/member/rina/ (theme `llas.default.js` /
/// `llas.default.css`, version 2.0.21).
///
/// This file only encodes the numbers and formulas taken verbatim from that
/// page's JS/CSS: it deliberately contains no SwiftUI. `RinaStarfield.swift`
/// turns these facts into drawn frames.
///
/// Source JS (runs once per page load):
/// ```js
/// var winw = $(window).width();
/// var field = $('.l-bg'); var items = 15;
/// for (var i = 0; i <= items; i++) {            // 16 elements
///   var icon = Math.ceil(Math.random() * 5);
///   var move = Math.ceil(Math.random() * 15);
///   var w_num = Math.round(Math.floor(Math.random() * winw) / winw * 100);
///   field.append('<p class="l-bg_item l-bg_item--' + icon + ' l-bg_item--move' + move + '" style="left:' + w_num + '%;"><span></span></p>');
/// }
/// ```
///
/// Source CSS facts are reproduced next to the values below.

// MARK: - Element shape

/// `l-bg_item--N`. There is no CSS rule for `--0` (Math.ceil can yield 0 when
/// `Math.random()` returns exactly 0), so that element renders nothing.
enum RinaStarAppearance: Int, CaseIterable {
    case item1 = 1
    case item2 = 2
    case item3 = 3
    case item4 = 4
    case item5 = 5
}

/// `l-bg_item--moveN`.
enum RinaStarMovement: Int, CaseIterable {
    case move0 = 0, move1, move2, move3, move4, move5, move6, move7
    case move8, move9, move10, move11, move12, move13, move14, move15
}

/// One `<p class="l-bg_item ...">` generated by the page-load loop.
struct RinaStarSourceElement: Equatable {
    /// `nil` when `icon == 0`: there is no matching CSS rule, so the element
    /// has no background image and no declared size (renders as 0x0).
    let appearance: RinaStarAppearance?
    let movement: RinaStarMovement
    /// CSS `left` percentage, 0...100 (element's left edge, not its centre).
    let leftPercent: Int
}

// MARK: - Appearance (size + image)

/// Resolved `.l-bg_item--N` (and, on narrow viewports, its
/// `@media screen and (max-width:767px)` override).
struct RinaStarAppearanceStyle: Equatable {
    let width: Double
    let height: Double
    let imageName: String

    /// - Parameter viewportWidth: the CSS `max-width:767px` breakpoint is
    ///   inclusive, so exactly 767 is "small" and 767.5 or 768 is "base".
    static func appearanceStyle(for appearance: RinaStarAppearance, viewportWidth: Double) -> RinaStarAppearanceStyle {
        let isSmall = viewportWidth <= 767
        switch appearance {
        case .item1:
            return isSmall
                ? RinaStarAppearanceStyle(width: 16, height: 16, imageName: "RinaBackgroundStar1")
                : RinaStarAppearanceStyle(width: 31, height: 31, imageName: "RinaBackgroundStar1")
        case .item2:
            return isSmall
                ? RinaStarAppearanceStyle(width: 16, height: 16, imageName: "RinaBackgroundStar2")
                : RinaStarAppearanceStyle(width: 31, height: 31, imageName: "RinaBackgroundStar2")
        case .item3:
            return isSmall
                ? RinaStarAppearanceStyle(width: 14, height: 14, imageName: "RinaBackgroundStar3")
                : RinaStarAppearanceStyle(width: 26, height: 27, imageName: "RinaBackgroundStar3")
        case .item4:
            return isSmall
                ? RinaStarAppearanceStyle(width: 10, height: 10, imageName: "RinaBackgroundStar4")
                : RinaStarAppearanceStyle(width: 20, height: 20, imageName: "RinaBackgroundStar4")
        case .item5:
            return isSmall
                ? RinaStarAppearanceStyle(width: 10, height: 10, imageName: "RinaBackgroundStar5")
                : RinaStarAppearanceStyle(width: 20, height: 20, imageName: "RinaBackgroundStar5")
        }
    }
}

// MARK: - Motion (rise duration + delay)

/// `--moveN { animation-duration: (12+2N)s; animation-delay: (0.5N)s; }`.
struct RinaStarMotionStyle: Equatable {
    let duration: TimeInterval
    let delay: TimeInterval

    static func motionStyle(for movement: RinaStarMovement) -> RinaStarMotionStyle {
        let n = Double(movement.rawValue)
        return RinaStarMotionStyle(duration: 12 + 2 * n, delay: 0.5 * n)
    }
}

// MARK: - Rise keyframes + spin duration (depend on DOM position, not on random values)

/// Which `top_anmN` keyframe rule applies to `.l-bg_item:nth-child(...)`.
///
/// `:nth-child(3n)` wins over the even/odd rules because it is declared
/// later in the stylesheet cascade, so a multiple of 3 always uses
/// `top_anm3` even when it is also even.
enum RinaStarRiseKeyframes: Equatable {
    case topAnm
    case topAnm2
    case topAnm3

    /// `top` at the animation's 0% keyframe, as a fraction of container height.
    var startTopFraction: Double {
        switch self {
        case .topAnm: return 1.05
        case .topAnm2: return 1.20
        case .topAnm3: return 1.50
        }
    }

    /// `top` at the animation's 100% keyframe, in points.
    var endTop: Double {
        switch self {
        case .topAnm: return -100
        case .topAnm2: return -170
        case .topAnm3: return -170
        }
    }

    /// `.l-bg_item { top: 105%; }` — the value shown before an element's
    /// `animation-delay` has elapsed (the animation has not started
    /// contributing a keyframe value yet).
    static let baseTopFraction: Double = 1.05

    /// `opacity` keyframes, identical across all three `top_anmN` rules:
    /// `0%{opacity:.3} 80%{opacity:.1} 100%{opacity:0}`.
    static let opacityKeyframes: [(fraction: Double, value: Double)] = [
        (0, 0.3), (0.8, 0.1), (1, 0)
    ]

    /// `animation-timing-function: cubic-bezier(0.39,0.575,0.565,1)`, applied
    /// independently to each keyframe segment of `top` and `opacity`.
    static let timingFunction = RinaCubicBezierTimingFunction(x1: 0.39, y1: 0.575, x2: 0.565, y2: 1)

    /// Interpolates `opacityKeyframes` at `progress` (0...1), easing each
    /// segment independently with `timingFunction` — the table is
    /// authoritative, so this is the only place the 0.3/0.1/0 values live.
    static func opacity(atProgress progress: Double) -> Double {
        let keyframes = opacityKeyframes
        for index in 0..<(keyframes.count - 1) {
            let (startFraction, startValue) = keyframes[index]
            let (endFraction, endValue) = keyframes[index + 1]
            guard progress <= endFraction || index == keyframes.count - 2 else { continue }
            let span = endFraction - startFraction
            let localProgress = span > 0 ? (progress - startFraction) / span : 0
            return startValue + (endValue - startValue) * timingFunction.solve(localProgress)
        }
        return keyframes.last?.value ?? 0
    }

    /// - Parameter childIndex: 1-based `nth-child` position (DOM order + 1).
    static func riseKeyframes(forChildIndex childIndex: Int) -> RinaStarRiseKeyframes {
        if childIndex % 3 == 0 { return .topAnm3 }
        return childIndex % 2 == 0 ? .topAnm : .topAnm2
    }

    /// `span { animation: rotate 5s ... }`, overridden by
    /// `:nth-child(5n) span` (4s) and `:nth-child(3n) span` (3s), with
    /// `:nth-child(even) span` (6s) beneath both in the cascade. 5n and 3n
    /// both win over even because they are declared later; 5n is declared
    /// after 3n, so a multiple of 15 uses 4s.
    static func spinDuration(forChildIndex childIndex: Int) -> TimeInterval {
        if childIndex % 5 == 0 { return 4 }
        if childIndex % 3 == 0 { return 3 }
        if childIndex % 2 == 0 { return 6 }
        return 5
    }
}

// MARK: - Element generation

enum RinaStarfieldSourceSpec {
    /// `for (var i = 0; i <= items; i++)` with `items = 15` → 16 iterations.
    static let elementCount = 16

    /// Fixed seed for screenshot mode (`-disableStarAnimation YES`), spelling
    /// "RINASTAR" in ASCII hex bytes.
    static let snapshotSeed: UInt64 = 0x5249_4E41_5354_4152

    /// App-side choice: screenshot mode freezes the field at this point in
    /// its cycle rather than at t=0 (which, per the source keyframes, shows
    /// no stars at all).
    static let snapshotTime: TimeInterval = 10

    /// Draws exactly three `Math.random()` values per element, in the same
    /// order as the source loop (icon, move, left).
    static func makeElements<G: RandomNumberGenerator>(using generator: inout G, viewportWidth: Int) -> [RinaStarSourceElement] {
        var elements: [RinaStarSourceElement] = []
        elements.reserveCapacity(elementCount)
        let winw = Double(viewportWidth)
        for _ in 0..<elementCount {
            let iconRandom = mathRandom(using: &generator)
            let moveRandom = mathRandom(using: &generator)
            let leftRandom = mathRandom(using: &generator)

            let icon = Int((iconRandom * 5).rounded(.up))
            let move = Int((moveRandom * 15).rounded(.up))
            let leftFraction = (leftRandom * winw).rounded(.down) / winw * 100
            let left = Int(jsRound(leftFraction))

            elements.append(RinaStarSourceElement(
                appearance: RinaStarAppearance(rawValue: icon),
                movement: RinaStarMovement(rawValue: move) ?? .move0,
                leftPercent: left
            ))
        }
        return elements
    }

    /// `Math.random()`: a double in [0, 1) built from 53 random mantissa bits.
    private static func mathRandom<G: RandomNumberGenerator>(using generator: inout G) -> Double {
        Double(generator.next() >> 11) * 0x1p-53
    }

    /// `Math.round(x)`: rounds half up (unlike Swift's round-half-to-even).
    private static func jsRound(_ x: Double) -> Double {
        (x + 0.5).rounded(.down)
    }
}

// MARK: - PRNG

/// SplitMix64, used to derive the fixed screenshot-mode layout from
/// `RinaStarfieldSourceSpec.snapshotSeed`.
struct RinaSplitMix64: RandomNumberGenerator {
    var state: UInt64

    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }
}

// MARK: - CSS cubic-bezier

/// Evaluates a CSS `cubic-bezier(x1,y1,x2,y2)` easing function: given a time
/// fraction `x` in [0, 1], solves for the bezier parameter `t` with
/// `bezierX(t) == x` (Newton's method, falling back to bisection), then
/// returns `bezierY(t)`.
struct RinaCubicBezierTimingFunction: Equatable {
    let x1: Double
    let y1: Double
    let x2: Double
    let y2: Double

    private static let precision = 1e-7

    /// - Parameter x: clamped to 0/1 outside (0, 1), matching CSS's handling
    ///   of out-of-range animation progress.
    func solve(_ x: Double) -> Double {
        if x <= 0 { return 0 }
        if x >= 1 { return 1 }
        let t = solveT(forX: x)
        return bezierCoordinate(t, y1, y2)
    }

    private func bezierCoordinate(_ t: Double, _ p1: Double, _ p2: Double) -> Double {
        let mt = 1 - t
        return 3 * mt * mt * t * p1 + 3 * mt * t * t * p2 + t * t * t
    }

    private func bezierXDerivative(_ t: Double) -> Double {
        let mt = 1 - t
        return 3 * mt * mt * x1 + 6 * mt * t * (x2 - x1) + 3 * t * t * (1 - x2)
    }

    private func solveT(forX x: Double) -> Double {
        var t = x
        for _ in 0..<8 {
            let xEstimate = bezierCoordinate(t, x1, x2) - x
            if abs(xEstimate) < Self.precision { return t }
            let derivative = bezierXDerivative(t)
            if abs(derivative) < 1e-6 { break }
            t -= xEstimate / derivative
        }

        var lo = 0.0
        var hi = 1.0
        t = min(max(t, 0), 1)
        while lo < hi {
            let xEstimate = bezierCoordinate(t, x1, x2)
            if abs(xEstimate - x) < Self.precision { return t }
            if xEstimate < x { lo = t } else { hi = t }
            t = (lo + hi) / 2
        }
        return t
    }
}
